version: '3.7'

services:
  redis:
    image: redis
    volumes:
      - redis-data:/data
  db:
    image: postgres
    restart: always
    env_file:
      - dev.env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "8989:5432"
  web:
    build: .
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    env_file:
      - dev.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  celery-worker:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A backend worker -l info"
    depends_on:
      - redis
      - web
    env_file:
      - dev.env
    volumes:
      - .:/code
  celery-beat:
    build: .
    command: bash -c "pip install -r requirements.txt && celery -A backend beat -l info"
    depends_on:
      - celery-worker
    env_file:
      - dev.env
    volumes:
      - .:/code
volumes:
  db-data:
    driver: local
  redis-data:
    driver: local