# Generated by Django 3.0.4 on 2020-04-05 11:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=15)),
                ('latitude', models.IntegerField(null=True)),
                ('longitude', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='owner',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='owner',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='route',
        ),
        migrations.AddField(
            model_name='cargo',
            name='shipment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Shipment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sign_up_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='category',
            field=models.CharField(choices=[('R', 'Regular wares'), ('C', 'Cold wares'), ('F', 'Frozen wares'), ('W', 'Warmed wares'), ('H', 'Hazardous materials')], default='R', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_targets', to='api.Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='starting_location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='shipment_sources', to='api.Location'),
            preserve_default=False,
        ),
    ]
