# Generated by Django 3.0.4 on 2020-04-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200405_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_geocoded',
            field=models.BooleanField(default=False),
        ),
    ]
