# Generated by Django 3.0.4 on 2020-03-16 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200316_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargo',
            old_name='owner',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='owner',
            new_name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='sign_up_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
