# Generated by Django 3.0.4 on 2020-04-27 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200410_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='destination_location',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='starting_location',
            new_name='origin',
        ),
    ]
