# Generated by Django 3.0.4 on 2020-04-27 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200427_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Truck'),
        ),
    ]
