# Generated by Django 3.0.4 on 2020-04-10 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_auto_20200410_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Default'), (1, 'Confirmed'), (2, 'Rejected')], default=0)),
                ('inner_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_inner', to='api.Shipment')),
                ('outer_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_outer', to='api.Shipment')),
            ],
        ),
    ]
