# Generated by Django 3.0.4 on 2020-04-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20200405_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('inner_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inner', to='api.Shipment')),
                ('outer_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outer', to='api.Shipment')),
            ],
        ),
    ]
