# Generated by Django 3.0.4 on 2020-04-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inner_shipment_pk', models.IntegerField()),
                ('outer_shipment_pk', models.IntegerField()),
            ],
        ),
    ]
