# Generated by Django 3.0.4 on 2020-04-05 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200405_1129'),
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='inner_shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_inner', to='api.Shipment'),
        ),
        migrations.AlterField(
            model_name='match',
            name='outer_shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_outer', to='api.Shipment'),
        ),
    ]
