# Generated by Django 3.0.4 on 2020-04-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20200405_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
