# Generated by Django 3.0.4 on 2020-04-26 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_auto_20200424_1228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RejectedMatch',
        ),
        migrations.AddField(
            model_name='match',
            name='inner_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
