# Generated by Django 3.0.4 on 2020-04-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_match_rejected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='confirmed',
        ),
        migrations.RemoveField(
            model_name='match',
            name='rejected',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.IntegerField(choices=[(0, 'Default'), (1, 'Confirmed'), (2, 'Rejected')], default=0),
        ),
    ]
