# Generated by Django 3.0.4 on 2020-04-27 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_auto_20200426_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='estimated_inner_arrival',
            new_name='estimated_inner_arrival_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='estimated_outer_arrival',
            new_name='estimated_inner_start_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='inner_start_time',
            new_name='estimated_outer_arrival_time',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='starting_time',
            new_name='start_time',
        ),
    ]
