# Generated by Django 3.0.4 on 2020-04-27 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_auto_20200427_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='inner_shipment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='outer_shipment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
